// Code generated by logcopter-gen; DO NOT EDIT.

package openaichat

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.llm-proxy.pkg.openaichat")
